"""Service supervisor abstraction: launchd (verified), systemd and Windows
scheduled tasks (generated output + dry-run plans only).

Real system mutation happens exclusively through :func:`apply_install` /
:func:`apply_uninstall` on the launchd backend. Every other path renders
deterministic definitions and command plans that tests can verify without
touching a real system.
"""

from __future__ import annotations

import dataclasses
import json
import os
import pathlib
import plistlib
import subprocess
import sys
from typing import Any

from .errors import BridgeError

DEFAULT_LABEL = "io.iron-triangle.bridge"


@dataclasses.dataclass(frozen=True)
class ServiceDefinition:
    label: str
    program: list[str]
    state_dir: str
    log_out: str
    log_err: str
    keepalive: bool = True

    def to_json(self) -> dict[str, Any]:
        return {
            "label": self.label,
            "program": list(self.program),
            "state_dir": self.state_dir,
            "log_out": self.log_out,
            "log_err": self.log_err,
            "keepalive": self.keepalive,
        }


def default_definition(config: dict[str, Any], config_path: pathlib.Path, bridge_path: pathlib.Path) -> ServiceDefinition:
    from .util import expand_path

    supervisor = config.get("supervisor") or {}
    directory = expand_path(config["state_dir"])
    label = str(supervisor.get("label") or config.get("launch_agent_label") or DEFAULT_LABEL)
    return ServiceDefinition(
        label=label,
        program=[sys.executable, str(bridge_path), "--config", str(config_path), "daemon"],
        state_dir=str(directory),
        log_out=str(directory / "bridge.stdout.log"),
        log_err=str(directory / "bridge.stderr.log"),
    )


# --- renderers ---------------------------------------------------------------


def render_launchd(defn: ServiceDefinition) -> bytes:
    payload = {
        "Label": defn.label,
        "ProgramArguments": list(defn.program),
        "RunAtLoad": True,
        "KeepAlive": defn.keepalive,
        "ProcessType": "Background",
        "StandardOutPath": defn.log_out,
        "StandardErrorPath": defn.log_err,
    }
    return plistlib.dumps(payload)


def render_systemd(defn: ServiceDefinition) -> str:
    unit_name = defn.label.replace(".service", "") + ".service"
    program = " ".join(_shell_quote(part) for part in defn.program)
    return "\n".join(
        [
            f"# Generated by iron-triangle; unit name: {unit_name}",
            "[Unit]",
            "Description=Iron Triangle supervised relay",
            "After=network-online.target",
            "Wants=network-online.target",
            "",
            "[Service]",
            "Type=simple",
            f"ExecStart={program}",
            "Restart=always" if defn.keepalive else "Restart=no",
            "RestartSec=5",
            f"StandardOutput=append:{defn.log_out}",
            f"StandardError=append:{defn.log_err}",
            "WorkingDirectory=" + defn.state_dir,
            "",
            "[Install]",
            "WantedBy=default.target",
            "",
        ]
    )


def render_windows_task(defn: ServiceDefinition) -> dict[str, Any]:
    """Scheduled-task plan for Windows. Rendered only; never applied by tests."""
    return {
        "task_name": defn.label,
        "command": _schtasks_create_command(defn),
        "restart_on_failure": defn.keepalive,
        "note": (
            "Windows support is generated-output only (experimental). "
            "Review the command before running it manually in an elevated shell."
        ),
    }


def _shell_quote(part: str) -> str:
    return "'" + part.replace("'", "'\\''") + "'"


def _schtasks_create_command(defn: ServiceDefinition) -> str:
    program = " ".join(f'"{part}"' if " " in part else part for part in defn.program)
    return (
        f'schtasks /Create /TN "{defn.label}" /SC ONLOGON /RL LIMITED '
        f'/TR "{program}" /F'
    )


# --- plans (dry-run surface) ---------------------------------------------------


def native_target() -> str:
    if sys.platform == "darwin":
        return "launchd"
    if sys.platform == "win32":
        return "windows-task"
    return "systemd"


def resolve_target(requested: str | None, config: dict[str, Any]) -> str:
    target = requested or (config.get("supervisor") or {}).get("target") or "auto"
    if target == "auto":
        return native_target()
    if target not in {"launchd", "systemd", "windows-task"}:
        raise BridgeError(f"unknown supervisor target: {target}")
    return target


def launchd_plist_path(config: dict[str, Any], defn: ServiceDefinition) -> pathlib.Path:
    from .util import expand_path

    configured = (config.get("supervisor") or {}).get("path") or config.get("launch_agent_path")
    if configured:
        return expand_path(str(configured))
    home = pathlib.Path(os.path.expanduser("~"))
    return home / "Library" / "LaunchAgents" / f"{defn.label}.plist"


def plan_install(target: str, config: dict[str, Any], defn: ServiceDefinition) -> dict[str, Any]:
    """A fully serializable install plan; applying it is a separate decision."""
    if target == "launchd":
        plist_path = launchd_plist_path(config, defn)
        domain = f"gui/{os.getuid()}"
        commands = [
            ["write", str(plist_path), "<rendered-plist-bytes>"],
            ["launchctl", "bootout", f"{domain}/{defn.label}"],
            ["launchctl", "bootstrap", domain, str(plist_path)],
            ["launchctl", "kickstart", f"{domain}/{defn.label}"],
        ]
        rendered = render_launchd(defn).decode("utf-8")
    elif target == "systemd":
        unit_name = f"{defn.label}.service"
        unit_dir = "~/.config/systemd/user"
        commands = [
            ["write", f"{unit_dir}/{unit_name}", "<rendered-unit-text>"],
            ["systemctl", "--user", "daemon-reload"],
            ["systemctl", "--user", "enable", "--now", unit_name],
        ]
        rendered = render_systemd(defn)
    elif target == "windows-task":
        commands = [["manual", render_windows_task(defn)["command"]]]
        rendered = json.dumps(render_windows_task(defn), ensure_ascii=False, indent=2)
    else:
        raise BridgeError(f"unknown supervisor target: {target}")
    return {"target": target, "definition": defn.to_json(), "rendered": rendered, "commands": commands}


def plan_uninstall(target: str, config: dict[str, Any], defn: ServiceDefinition) -> dict[str, Any]:
    if target == "launchd":
        plist_path = launchd_plist_path(config, defn)
        domain = f"gui/{os.getuid()}"
        commands = [
            ["launchctl", "bootout", f"{domain}/{defn.label}"],
            ["remove", str(plist_path)],
        ]
    elif target == "systemd":
        unit_name = f"{defn.label}.service"
        commands = [
            ["systemctl", "--user", "disable", "--now", unit_name],
            ["remove", f"~/.config/systemd/user/{unit_name}"],
            ["systemctl", "--user", "daemon-reload"],
        ]
    elif target == "windows-task":
        commands = [["manual", f'schtasks /Delete /TN "{defn.label}" /F']]
    else:
        raise BridgeError(f"unknown supervisor target: {target}")
    return {"target": target, "label": defn.label, "commands": commands}


# --- apply (real mutation; macOS launchd only, preserved from v0.1) ----------


def apply_install_launchd(config: dict[str, Any], defn: ServiceDefinition) -> dict[str, Any]:
    if sys.platform != "darwin":
        raise BridgeError("apply_install_launchd is only supported on darwin; use --dry-run elsewhere")
    plist_path = launchd_plist_path(config, defn)
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = plist_path.with_name(f".{plist_path.name}.{os.getpid()}.tmp")
    tmp.write_bytes(render_launchd(defn))
    os.replace(tmp, plist_path)
    domain = f"gui/{os.getuid()}"
    subprocess.run(["launchctl", "bootout", f"{domain}/{defn.label}"], check=False, capture_output=True)
    result = subprocess.run(
        ["launchctl", "bootstrap", domain, str(plist_path)],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise BridgeError(f"launchctl bootstrap failed: {result.stderr.strip()}")
    subprocess.run(["launchctl", "kickstart", f"{domain}/{defn.label}"], check=False, capture_output=True)
    return {"installed": True, "label": defn.label, "plist": str(plist_path)}


def apply_uninstall_launchd(config: dict[str, Any], defn: ServiceDefinition) -> dict[str, Any]:
    if sys.platform != "darwin":
        raise BridgeError("apply_uninstall_launchd is only supported on darwin; use --dry-run elsewhere")
    plist_path = launchd_plist_path(config, defn)
    domain = f"gui/{os.getuid()}"
    subprocess.run(["launchctl", "bootout", f"{domain}/{defn.label}"], check=False, capture_output=True)
    removed = False
    if plist_path.exists():
        plist_path.unlink()
        removed = True
    return {"uninstalled": True, "label": defn.label, "plist_removed": removed}
